# Generated by Django 4.2.23 on 2025-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raw_html',
            field=models.TextField(blank=True),
        ),
    ]
