# Generated by Django 4.2.23 on 2025-08-13 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_created_at_job_company_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='valid_through',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('link', 'source'), name='uniq_job_per_source'),
        ),
    ]
